include("${CMAKE_CURRENT_LIST_DIR}/aarch64-linux-gnu.toolchain.cmake")

if (DEFINED ENV{TARGET_RUNTIME_SYSROOT} AND IS_DIRECTORY "$ENV{TARGET_RUNTIME_SYSROOT}")
  set(_TARGET_RUNTIME_SYSROOT "$ENV{TARGET_RUNTIME_SYSROOT}")
  set(_TARGET_RUNTIME_LINK_FLAGS
      "-L${_TARGET_RUNTIME_SYSROOT}/usr/lib -L${_TARGET_RUNTIME_SYSROOT}/lib -Wl,-rpath-link,${_TARGET_RUNTIME_SYSROOT}/usr/lib -Wl,-rpath-link,${_TARGET_RUNTIME_SYSROOT}/lib -Wl,--dynamic-linker=/lib/ld-linux-aarch64.so.1 -Wl,--allow-shlib-undefined")
  string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${_TARGET_RUNTIME_LINK_FLAGS}")
  string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT " ${_TARGET_RUNTIME_LINK_FLAGS}")
  set(_TARGET_RUNTIME_C_LIBRARIES "${_TARGET_RUNTIME_SYSROOT}/lib/libc.so.6")
  set(_TARGET_RUNTIME_CXX_LIBRARIES
      "${_TARGET_RUNTIME_SYSROOT}/usr/lib/libstdc++.so"
      "${_TARGET_RUNTIME_SYSROOT}/lib/libm.so.6"
      "${_TARGET_RUNTIME_SYSROOT}/lib/libc.so.6")
  foreach (_TARGET_RUNTIME_OPTIONAL_LIBRARY
           "${_TARGET_RUNTIME_SYSROOT}/usr/lib/libgcc_s.so.1"
           "${_TARGET_RUNTIME_SYSROOT}/lib/libgcc_s.so.1")
    if (EXISTS "${_TARGET_RUNTIME_OPTIONAL_LIBRARY}")
      list(APPEND _TARGET_RUNTIME_CXX_LIBRARIES "${_TARGET_RUNTIME_OPTIONAL_LIBRARY}")
    endif ()
  endforeach ()

  string(APPEND CMAKE_C_STANDARD_LIBRARIES_INIT " ${_TARGET_RUNTIME_C_LIBRARIES}")
  foreach (_TARGET_RUNTIME_CXX_LIBRARY IN LISTS _TARGET_RUNTIME_CXX_LIBRARIES)
    string(APPEND CMAKE_CXX_STANDARD_LIBRARIES_INIT " ${_TARGET_RUNTIME_CXX_LIBRARY}")
  endforeach ()
endif ()
